alist = []
x = int(input("Please enter a number: "))
alist.append(x)
y = int(input("Please enter a number: "))
alist.append(y)
z = int(input("Please enter a number: "))
alist.append(z)
a = int(input("Please enter a number: "))
alist.append(a)
b = int(input("Please enter a number: "))
alist.append(b)
print("this is your list ",alist)
alist.reverse()
print("this is the reversed list ",alist)
